### ISSUE TITLE
small error in doc for symfony

### ISSUE THREAD

**Issue by adipasquale** [jmhobbs/Swiftmailer-Transport--AWS-SES#15]
Thanks for this (still) useful piece of code, as my shared hosting has closed port 465 !

I think I've noticed a small typo in your symfony config code : 

``` yaml
# app/frontend/config/factories.yml

all:
  mailer:
    class: sfMailer
    param:
      transport:
        accessKeyId:    your-access-key
        secretKey:      Y0uR-$3cr3t5-k3y
        debug:          false
        endpoint:       'https://email.us-east-1.amazonaws.com/' # make sure to use trailing slash !
```

where it's supposed to be : 

``` yaml
# app/frontend/config/factories.yml

all:
  mailer:
    class: sfMailer
    param:
        transport:
          class:          Swift_AWSTransport
          param:
            accessKeyId:    your-access-key
            secretKey:      Y0uR-$3cr3t5-k3y
            debug:          false
            endpoint:       'https://email.us-east-1.amazonaws.com/' # make sure to use trailing slash !
```

(by the way the right tag for github format is ```yaml )
